apiVersion: v1
kind: Pod
metadata:
  name: "nginx-label-1"
  namespace: default
  labels:
    app: "nginx-label-1"
    tier: web
spec:
  containers:
    - name: nginx-label-1
      image: "nginx:latest"
      ports:
        - containerPort: 80
          name: http
  restartPolicy: Never
