apiVersion: v1
kind: Pod
metadata:
  name: "annotation-pod-1"
  annotations:
    created-by: "borisleighton@gmail.com"
    purpose: "Ejemplo de uso de anotaciones"
    monitoring: "enabled"
  namespace: default
  labels:
    app: "annotation-pod-1"
spec:
  containers:
    - name: annotation-pod-1
      image: "nginx:latest"
      ports:
        - containerPort: 80
          name: http
  restartPolicy: Always
