apiVersion: v1
kind: Pod
metadata:
  name: "sample-pod-1"
  namespace: default
  labels:
    app: "sample-pod-1"
spec:
  containers:
    - name: sample-pod-1
      image: "nginx:latest"
      ports:
        - containerPort: 80
          name: http
  restartPolicy: Always
